#!/bin/sh
# GENERATED: DO NOT MODIFY
# templates/scripts/spec_to_e2e_gen.sh.template
#
# derived-from: SUBAGENT-DEVSYS-7PHASE-TEST-DEPLOY-V1 (PO 直命 2026-05-04 PO-DIRECTIVE-014)
# spec-ref: core_spec.md §2.25.21 (Primary Quality Gate Inversion) +
#           docs/po-decisions.md PO-DIRECTIVE-014 (7 phase 開発ワークフロー 機械強制) +
#           7 phase ワークフロー phase 5 「仕様 → E2E spec.ts 自動生成」 機械強制 path
#
# 用途:
#   goal-ai-worker の feature_spec.md を scan → 受入条件 (Acceptance Criteria) を抽出 → Playwright E2E
#   spec.ts 雛形 を `tests/e2e/specs/{feature_id}.gen.spec.ts` に生成。 既存 file は上書きせず skip。
#   生成された spec.ts は npx playwright test で実行可能な形式 (= test('', async ({ page }) => {...}))。
#
# Phase 5 連携:
#   - dev-system phase 5 「spec → E2E spec.ts 自動生成」 真値 entry point
#   - 7 phase: コンセプト → 仕様書 → 実装 → 仕様↔実装一致 test → spec通り動くか test → 実機 test → 配布
#   - 本 script = 「spec通り動くか test」 (= phase 5) の 自動化 雛形 生成器
#
# Placeholders:
#   goal-ai-worker: 生成 App 名 (識別子、ログ出力で使用)
#
# Usage:
#   sh scripts/spec_to_e2e_gen.sh                        # 既定 spec_dir で 実行 (= 全 spec scan)
#   sh scripts/spec_to_e2e_gen.sh --dry-run              # dry run (生成せず scan 件数 のみ表示)
#   sh scripts/spec_to_e2e_gen.sh --spec-dir <dir>       # spec_dir 指定
#   sh scripts/spec_to_e2e_gen.sh --output-dir <dir>     # 出力 dir 指定
#
# 完了条件:
#   - exit 0 = 正常完了 (scan + 生成 完了、 既存 file は skip)
#   - exit 1 = scan / 書込み エラー
#
# POSIX sh 互換 (bash 機能 不使用)。

set -e

DRY_RUN=0
SPEC_DIR="docs/spec"
OUTPUT_DIR="tests/e2e/specs"
APP_NAME="${APP_NAME:-goal-ai-worker}"

# 引数 parse
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --spec-dir)
      SPEC_DIR="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --help|-h)
      echo "Usage: $0 [--dry-run] [--spec-dir <dir>] [--output-dir <dir>]"
      exit 0
      ;;
    *)
      echo "[spec_to_e2e_gen][goal-ai-worker] WARN: unknown arg: $1"
      shift
      ;;
  esac
done

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT" || exit 1

echo "================================================================"
echo "  spec_to_e2e_gen.sh — phase 5 (spec → E2E spec.ts 自動生成)"
echo "  app: goal-ai-worker"
echo "================================================================"
echo "  REPO_ROOT  : $REPO_ROOT"
echo "  SPEC_DIR   : $SPEC_DIR"
echo "  OUTPUT_DIR : $OUTPUT_DIR"
echo "  DRY_RUN    : $DRY_RUN"
echo "----------------------------------------------------------------"

SCAN_COUNT=0
GEN_COUNT=0
SKIP_COUNT=0

if [ ! -d "$REPO_ROOT/$SPEC_DIR" ]; then
  echo "[spec_to_e2e_gen][goal-ai-worker] INFO: spec dir 不在 ($SPEC_DIR) → scan_count=0、 phase 2 spec template 配備 後 真生成可"
  echo "[spec_to_e2e_gen][goal-ai-worker] result: scan=$SCAN_COUNT 件、 gen=$GEN_COUNT 件、 skip=$SKIP_COUNT 件"
  exit 0
fi

if [ "$DRY_RUN" = "0" ]; then
  mkdir -p "$REPO_ROOT/$OUTPUT_DIR"
fi

FOUND_SPECS=$(find "$REPO_ROOT/$SPEC_DIR" -type f \( -name "*_spec.md" -o -name "feature_*.md" -o -name "spec_*.md" \) 2>/dev/null || true)

if [ -z "$FOUND_SPECS" ]; then
  echo "[spec_to_e2e_gen][goal-ai-worker] INFO: spec file 0 件 (= phase 2 spec template 配備 後 真生成可)"
  echo "[spec_to_e2e_gen][goal-ai-worker] result: scan=$SCAN_COUNT 件、 gen=$GEN_COUNT 件、 skip=$SKIP_COUNT 件"
  exit 0
fi

for SPEC_FILE in $FOUND_SPECS; do
  SCAN_COUNT=$((SCAN_COUNT + 1))
  SPEC_BASENAME=$(basename "$SPEC_FILE" .md)
  FEATURE_ID=$(echo "$SPEC_BASENAME" | tr -c 'A-Za-z0-9_-' '_' | sed 's/__*/_/g' | sed 's/_$//')
  GEN_FILE="$OUTPUT_DIR/${FEATURE_ID}.gen.spec.ts"

  echo "[spec_to_e2e_gen][goal-ai-worker] scan: $SPEC_FILE → $GEN_FILE"

  if [ "$DRY_RUN" = "1" ]; then
    continue
  fi

  if [ -f "$REPO_ROOT/$GEN_FILE" ]; then
    echo "[spec_to_e2e_gen][goal-ai-worker] SKIP: $GEN_FILE 既存 (上書き禁止)"
    SKIP_COUNT=$((SKIP_COUNT + 1))
    continue
  fi

  ACCEPTANCE_LINES=$(awk '
    /^## (受入条件|Acceptance Criteria)/ { in_section = 1; next }
    /^## / && in_section { in_section = 0 }
    in_section && /^- / { print }
  ' "$SPEC_FILE" 2>/dev/null | head -10 || true)

  CRITERIA_COUNT=$(echo "$ACCEPTANCE_LINES" | grep -c '^- ' 2>/dev/null || echo 0)
  CRITERIA_COUNT=$(echo "$CRITERIA_COUNT" | tr -d ' ')

  cat > "$REPO_ROOT/$GEN_FILE" <<EOF
/*
 * GENERATED by scripts/spec_to_e2e_gen.sh — DO NOT MODIFY 自動生成
 *
 * app: goal-ai-worker
 * derived-from: ${SPEC_FILE}
 * feature_id: ${FEATURE_ID}
 * generated_at: $(date -u +%FT%TZ)
 * acceptance_criteria_count: ${CRITERIA_COUNT}
 *
 * 7 phase ワークフロー phase 5 「spec → E2E spec.ts 自動生成」 雛形:
 *   - コンセプト → 仕様書 → 実装 → spec通り動くか test (= 本 spec) → 実機 test → 配布
 *   - 受入条件 (Acceptance Criteria) を Playwright assert 化、 npx playwright test で実行
 *
 * Run:
 *   npx playwright test ${OUTPUT_DIR}/${FEATURE_ID}.gen.spec.ts
 *
 * 仕様根拠:
 *   - core_spec.md §2.25.21 (Primary Quality Gate Inversion)
 *   - docs/po-decisions.md PO-DIRECTIVE-014 (7 phase 機械強制)
 */
import { test, expect } from '@playwright/test';

const BASE = process.env.FRONTEND_BASE || process.env.BASE_URL || 'http://localhost:5173';

test.describe('[gen] ${FEATURE_ID} — Playwright E2E (acceptance criteria 自動 verify)', () => {
  test.describe.configure({ mode: 'serial' });

  test('Step 1: visit feature page (smoke)', async ({ page }) => {
    await page.goto(BASE);
    await expect(page).toHaveURL(/.+/);
  });

EOF

  if [ "$CRITERIA_COUNT" -gt 0 ]; then
    STEP_NUM=2
    OLD_IFS="$IFS"
    IFS='
'
    for CRITERION in $ACCEPTANCE_LINES; do
      CRITERION_CLEAN=$(echo "$CRITERION" | sed 's/^- //' | sed "s/'/\\\\'/g")
      cat >> "$REPO_ROOT/$GEN_FILE" <<EOF
  test('Step ${STEP_NUM}: ${CRITERION_CLEAN}', async ({ page }) => {
    await page.goto(BASE);
  });

EOF
      STEP_NUM=$((STEP_NUM + 1))
    done
    IFS="$OLD_IFS"
  fi

  cat >> "$REPO_ROOT/$GEN_FILE" <<'EOF'
});
EOF

  GEN_COUNT=$((GEN_COUNT + 1))
  echo "[spec_to_e2e_gen][goal-ai-worker] GEN: $GEN_FILE (criteria=$CRITERIA_COUNT)"
done

echo "----------------------------------------------------------------"
echo "[spec_to_e2e_gen][goal-ai-worker] result: scan=$SCAN_COUNT 件、 gen=$GEN_COUNT 件、 skip=$SKIP_COUNT 件"
echo "[spec_to_e2e_gen][goal-ai-worker] phase 5 (spec → E2E spec.ts 自動生成) 完了"
echo "================================================================"

exit 0
